version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  node:
    container_name: nukebot-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongodb

volumes:
  mongodata:

networks:
  default:
    external:
      name: nukebot